### ISSUE TITLE
document environment variables

### ISSUE THREAD

**Issue by brentp** [uab-cgds-worthey/quac#66]
This command:
```
python src/run_quac.py --project_name test_project --projects_path ./.test/ngs-data/ --pedigree .test/configs/no_priorQC/project_2samples.ped --outdir "quac-out" --exome -e="--conda-create-envs-only"
```
gives:
```
usage: run_quac.py [-h] [--project_name] [--projects_path] [--pedigree] [--quac_watch_config] [--workflow_config] [--outdir] [--tmp_dir] [--exome] [--include_prior_qc]
                   [--allow_sample_renaming] [--subtasks_slurm] [--cluster_config] [--log_dir] [-e] [-n] [--snakemake_slurm] [--rerun_failed] [--slurm_partition]
run_quac.py: error: The directory '$USER_SCRATCH/tmp/quac/tmp' does not exist!
```

as far as I can tell, the `USER_SCRATCH` environment variable is not documented. Even if I do: 
```
export USER_SCRATCH=.
```
I get the same error.
If I make the directory in the error then it errors with:
```
run_quac.py: error: The directory '$USER_SCRATCH/tmp/quac/logs' does not exist!
```
please provide a better error or simply create this subdirectory structure.

**Comment by brentp** [comment]
when I make those directories myself, I see:
```
$ python src/run_quac.py --project_name test_project --projects_path ./.test/ngs-data/ --pedigree .test/configs/no_priorQC/project_2samples.ped --outdir "quac-out" --exome -e="--conda-create-envs-only" --quac_watch_config configs/quac_watch/exome_quac_watch_config.yaml
########################################
Command to run the pipeline:
snakemake \
	--snakefile '/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/workflow/Snakefile' \
	--config project_name='test_project' projects_path='/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/.test/ngs-data' ped='/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/.test/configs/no_priorQC/project_2samples.ped' quac_watch_config='/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/configs/quac_watch/exome_quac_watch_config.yaml' workflow_config='/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/configs/workflow.yaml' unique_id='5567f82b-4ea7-4546-a46e-2635bd216870' out_dir='/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/quac-out' log_dir='/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/tmp/quac/logs' exome='True' include_prior_qc_data='False' allow_sample_renaming='False' \
	--restart-times 1 \
	--use-conda \
	--use-singularity \
	--singularity-args '--cleanenv --bind /scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/tmp/quac/tmp:/tmp --bind /scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/quac-out,/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/.test/ngs-data/test_project/analysis,/data/project/worthey_lab/manual_datasets_central/verifyBamID/2.0.1/resource/wgs,/data/project/worthey_lab/manual_datasets_central/verifyBamID/2.0.1/resource/exome/chr_added,/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/configs/quac_watch/exome_quac_watch_config.yaml,/data/project/worthey_lab/manual_datasets_central/somalier/0.2.13/ancestry,/data/project/worthey_lab/manual_datasets_central/somalier/0.2.13/sites,/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/tmp/quac/logs,/data/project/worthey_lab/datasets_central/human_reference_genome/processed/GRCh38/no_alt_rel20190408,/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/.test/configs/no_priorQC' \
	--profile '/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/src/slurm/slurm_profile' \
	--conda-create-envs-only
########################################

Slurm job name   : "quac-2023-04-03T18.14.29.236137"
Slurm job script : "/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/tmp/quac/logs/quac-2023-04-03T18.14.29.236137.sh"
Config file /scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/configs/workflow.yaml is extended by additional config specified via the command line.
// Processing project: test_project
// Project path: "/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/.test/ngs-data/test_project/analysis"
// Exome mode: True
// Include prior QC data: False
// WARNING: '.test' present in the path supplied via --projects_path. So testing mode is used.
Building DAG of jobs...
MissingInputException in rule somalier_extract in file /scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/workflow/rules/relatedness_ancestry.smk, line 1:
Missing input files for rule somalier_extract:
    output: /scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/quac-out/project_level_qc/somalier/extract/C.somalier
    wildcards: sample=C
    affected files:
        /data/project/worthey_lab/datasets_central/human_reference_genome/processed/GRCh38/no_alt_rel20190408/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
        /data/project/worthey_lab/manual_datasets_central/somalier/0.2.13/sites/sites.hg38.vcf.gz
Traceback (most recent call last):
  File "/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/src/run_quac.py", line 372, in <module>
    main(ARGS)
  File "/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/src/run_quac.py", line 202, in main
    submit_slurm_job(pipeline_cmd, job_dict)
  File "/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/src/slurm/submit_slurm_job.py", line 60, in submit_slurm_job
    job_id = slurm_job.run(**params_dict)
  File "/scratch/ucgd/lustre-work/quinlan/u6000771/miniconda3/envs/hts/lib/python3.10/site-packages/slurmpy/slurmpy.py", line 171, in run
    res = subprocess.check_output(args).strip()
  File "/scratch/ucgd/lustre-work/quinlan/u6000771/miniconda3/envs/hts/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/scratch/ucgd/lustre-work/quinlan/u6000771/miniconda3/envs/hts/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '/scratch/ucgd/lustre-work/quinlan/u6000771/src/quac/tmp/quac/logs/quac-2023-04-03T18.14.29.236137.sh']' returned non-zero exit status 1.
```

**Comment by ManavalanG** [comment]
Hi @brentp, thanks for reviewing QuaC and reporting issues.

1. Regarding `$USER_SCRATCH` and forcing user to create the directories, I have now refactored `src/run_quac.py` to remove usage `$USER_SCRATCH` and auto-create user-provided directories. It is under review (#67) now, and I will let you know once it is merged.
2. Regarding the error message posted here (`Missing input files for rule somalier_extract`), it appears the dataset dependencies necessary for QuaC are not made available. If so, please see [directions here](https://quac.readthedocs.io/en/latest/reqts_configs/#set-up-workflow-config-file) on using our script to set up all necessary dataset dependencies.
